### ISSUE TITLE
Subject field of recommendation request email

### ISSUE THREAD

**Issue by longpd** [Cooperation-org/linked-claims-author#164]
In the predefined template text for the recommender email the Subject field currently reads: "Support Request: software tester". Coming from the skills credential author in LinkedClaims this sounds like a software error message report. 

Please change it to "Request for an endorsement for my self-claimed skill".

**Comment by dev-mhany** [comment]
![image](https://github.com/user-attachments/assets/e962d6b3-bcf1-484c-890b-7f27d90aec8a)
![image](https://github.com/user-attachments/assets/6b31a624-b565-4173-8910-e6638259b893)
DOne
