### ISSUE TITLE
do not import from test in the running code

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#166]
`import ComprehensiveClaimDetails from '../../test/[id]/ComprehensiveClaimDetails'`

really guys!

in `/linked-claims-author/app/view/[id]/page.tsx`

**Comment by AmrNabel** [comment]
Muhammad named the folder Test but it is not for the test, I will change it and please Muhammed be careful with Folder naming

**Comment by dev-mhany** [comment]
@gvelez17 @AmrNabel 
Ok

**Comment by dev-mhany** [comment]
Resolved in #168
