### ISSUE TITLE
as a new user coming to recommendation flow, the main page image seems to keep loading

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#180]
![Image](https://github.com/user-attachments/assets/06bbc4e5-4556-4f3e-b795-dbad85c309ac)

when logging in as a new google user who has not used the app before, the page seems to just keep loading, when starting at the recommendation flow page

it does work if i click the button, but the main image never loaded

**Comment by dev-mhany** [comment]
![image](https://github.com/user-attachments/assets/b693edf7-c8aa-4c8b-97ba-5f1bbb85c26d)
