### ISSUE TITLE
as a new user performing a recommendation, Finish & Sign hangs

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#181]
The spinner continues to spin and we never get past the "Finish and Sign' page

![Image](https://github.com/user-attachments/assets/5ca237a8-a5c7-4e86-9eb7-ccd071d72d9e)

this user has never created a credential, and started using the app as a recommender

**Comment by gvelez17** [comment]
I notice that this new user, does not have the VCs folder in their drive

![Image](https://github.com/user-attachments/assets/f31affb2-9036-4654-aedd-245ad5c93c32)

**Comment by 0marSalah** [comment]
explain more, what do you mean with started using 'the app as a recommender'

and is there is no VC folder and user hit finish&sign, we will create a new folder

**Comment by 0marSalah** [comment]
any ay this issue happened because we have a problem with the scope that Amr mentioned in slack
