### ISSUE TITLE
Upload of evidence reorder in skill assertion cred

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#195]
An individual creating a skill credential is asked to upload evidence that conveys something about their actual ability to perform the skill. In this case, the first thing uploaded is also 'featured' on the credential when rendered.  The 2nd and remaining uploaded evidence entires are listed as hypertext links using the name of the object. The credential author should be able to reorder the list as they may find a better piece of evidence after they've uploaded the first and want to use that for the featured representation the skill. It's likely this would be best if it were an image file and not another object type.

**Comment by AmrNabel** [comment]
this is already working now on the app you can check again, when see set many images ass evidence the first one have featured icon and when you need to make another one as the mail one you can click on feature icon of it to make it the main one

**Comment by Gitongamiriam** [comment]
Need to add instructions to the user to click to make featured
