### ISSUE TITLE
Implement “wait” page on saving consistently, while write is in process

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#196]
When a write to GDrive is invoked  both the self-issued credential author and the recommender credential author should see a page that just has the rotating 'in progress' wheel  with a short note saying "Saving credential. Patience is a virtue."

The current wait page for the write process is shown as spinning wheel in the top rectangular box with other options listed below it. If other options on that page are clicked while waiting for the save to complete it will end the save process and take the author back to the start of the recommendation workflow. 

Present a separate saving screen, then go to a page with options

The last phrase there might be a bit cheeky so amend it as you think best ;-)

**Comment by AmrNabel** [comment]
done, adding the lading page to the success page and recommendation page 
this is the PR 
https://github.com/Cooperation-org/linked-claims-author/pull/207
