### ISSUE TITLE
Upload evidence supporting recommender bonafides

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#197]
The recommender author should be able to upload evidence of their credibility to make the recommendation by both pointing to an object with a URL link to a publicly accessible location, or be able to upload evidence that might be on their local machine's drive. (As per the self-issuer of the recommendation, they should also be able to reorder this  list of evidence supporting their bonafides).

**Comment by AmrNabel** [comment]
so we need to add input for the links right ?

**Comment by longpd** [comment]
> so we need to add input for the links right ?

Yes. We need both the Self-assertion of a skills credential workflow AND the Recommendation Workflow support uploading content from one's local machine and pointing to content located a publicly accessible URL.

**Comment by AmrNabel** [comment]
so can we made a custom one for this like the inputs we did in the app or should wait Karen to make one

**Comment by longpd** [comment]
We should try to model the wireframes Karen provided. I think she had something for this purpose in the figma work she shared. She has no further room in her work to do more on this version of LinkedClaims. She is in the contract for business extensions, so-called, which puts the issuing of linkedclaims associated not with individual but with a person representing a company either as a supervisor or employee.

I suggest you should look carefully at the last set of figma wireframes to see how she suggested implementing upload and URL links to evidence.

**Comment by AmrNabel** [comment]
ok no problem we will handle that
