### ISSUE TITLE
Write recommender credential to the Recommender’s GDrive

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#198]
Currently the recommender credential is encoded as a comment on in the Gdoc that corresponds to the Self-issued Skill Credential. The recommender should have their own credential in their own GDrive both for a record of what they've recommended, as well as the agency it gives by allowing them to delete it if they wish to remove the recommendation.

**Comment by 0marSalah** [comment]
we already store the recommendation in recommender google drive, in the current version and the future version that i am working on
here is the issue https://github.com/Cooperation-org/linked-claims-storage/issues/27

please close this issue i think its not necessary, thank you

**Comment by AmrNabel** [comment]
right
