### ISSUE TITLE
“Ask for Recommendation” sample txt of request w/ “copy this text …” to paste in mailer. If mailer is installed, unnecessary. Force past of sample txt into addressed but empty email

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#202]
“Ask for Recommendation” sample txt of request w/ “copy this text …” to paste in mailer. If mailer is installed, unnecessary. Force paste of sample txt into addressed but empty email 
Also, when clicking on open email it gives a pop up that the text has been save successfully then it opens tabs on the background - And the up button is it a button or an instruction. because when you click it it appears to work as a button

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/fc0e7040-0396-40b2-832e-23ceb04c23fa)
![Image](https://github.com/user-attachments/assets/00823a2d-78f1-42a1-b184-d643ef9148c2)
![Image](https://github.com/user-attachments/assets/68e89641-c01d-4a69-90c5-834c5dc9da92)
![Image](https://github.com/user-attachments/assets/5b420ced-7717-4d5a-a6bd-785338f35cba)
@Gitongamiriam

**Comment by Gitongamiriam** [comment]
Demostrated on the Friday call

**Comment by Gitongamiriam** [comment]
Make the copy button visible 
Make it an action button

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/f869628c-2495-4b08-9dd3-c3717c986b5f)

**Comment by gvelez17** [comment]
in the authoring flow

<img width="917" alt="Image" src="https://github.com/user-attachments/assets/6b2164bd-4093-4c42-b4ea-537da63b776c" />

**Comment by Gitongamiriam** [comment]
The action button should be  consistent between the authoring flow and recommender flow

**Comment by Gitongamiriam** [comment]
Check the wireframe to see how this page appears

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/ef51e251-f69a-4104-bdf9-d41775bd23db)

**Comment by dev-mhany** [comment]
i found that t askforRecommendation page in figma is just and extend of the success page

**Comment by Gitongamiriam** [comment]
Ask Karen after sending recommendation whats the next  step on that
