### ISSUE TITLE
pick new domain

### ISSUE THREAD

**Issue by gvelez17** [Cooperation-org/linked-claims-author#209]
We have to move from opencreds.net

LinkedCreds.com is available, i'm reserving that in case

some other options:

SkillPass.net
CredPort.me
YourSkills.me
Verifiable.us
myskills.world

Lets pick this within the week?  we have to adjust our google app application with it i believe also.

**Comment by gvelez17** [comment]
verifiable.me is taken, we could pay a $70 broker fee to godaddy.com to find out if they would sell it, but there are no guarantees even if we pay the broker fee.

**Comment by gvelez17** [comment]
hey so Taylor wants access to have his legal team vet these, i moved these to a spreadsheet and added some more, the master list is now at https://docs.google.com/spreadsheets/d/1-aduKIffphWlkqZTpd17Epq7f7p8cY5zHiYRagJjyVQ/edit?gid=0#gid=0

**Comment by Gitongamiriam** [comment]
Taylor picked allskillscount.org for the domain

**Comment by 0marSalah** [comment]
done!

check it out linkedclaim-author.allskillscount.org

**Comment by Gitongamiriam** [comment]
Waiting for confirmation to get off from the OpenCreds.
