### ISSUE TITLE
Remove the decline screen

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#216]
1 Rename the decline button to Decline/Ignore 
2 When the users presses that button the screen should say -  no further action is  neccessary. We encourage you to respond to the requestor as appropriate.

**Comment by Gitongamiriam** [comment]
There's no decline screen on our wireframes

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/04cf4ac3-be59-4b46-a2a2-01afc9974899)
