### ISSUE TITLE
Rename connect to google button

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#217]
Change connect to google button to log in with google. If the user is already logged in  then skip the screen and go to step 2.

**Comment by dev-mhany** [comment]
![Image](https://github.com/user-attachments/assets/5c343d1f-06b1-4813-afea-f11db2fb21e3)
if i got the user to skip this step how will he continue without saving in case he already logged in but don't want to save this cred/recom in his drive ?

**Comment by Gitongamiriam** [comment]
Make sure the styling of the button matches the font  to make sure all the fonts are same
