### ISSUE TITLE
Create UI for display of reccommendation

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#218]
Create the UI for the requestor accept recommendation screen (currently it just display the raw json)
buttons on the bottom should say Accept and ignore.
Clicking on the accept button should take the user to the view page .

**Comment by Gitongamiriam** [comment]
Kindly add a screenshot to this.

**Comment by AmrNabel** [comment]
![Image](https://github.com/user-attachments/assets/1ae84ee6-c058-4e12-9c12-c81b52c776e6)

**Comment by Gitongamiriam** [comment]
Check on the grammar in this part on vouch wording
