### ISSUE TITLE
Make sure the all the buttons and fonts correspond to the wireframes

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#241]
Make sure the styling of the button matches the font to make sure all the fonts are same

Re use the class components

on the vertical ellipses for the My Skills page so we don't lose the feedback. On the menu that opens, the links should match what's shown in the attached image (this is how it works in the wireframes). The colors need to match, as well, as the colors in the screen share I saw had color contrast violations from an accessibility perspective.![Image](https://github.com/user-attachments/assets/5b7dc62c-18b1-4909-b663-22fa91326787)

**Comment by AmrNabel** [comment]
done ![Image](https://github.com/user-attachments/assets/0a69e90d-2529-432e-860a-820197ffa858)

**Comment by AmrNabel** [comment]
![Image](https://github.com/user-attachments/assets/2df97382-1091-481b-a032-f86a30696d1e)
![Image](https://github.com/user-attachments/assets/028609a7-8615-47ab-afa8-658455c10dba)
![Image](https://github.com/user-attachments/assets/860158d5-5764-4e4f-9b5d-0d2286191307)

**Comment by Gitongamiriam** [comment]
Demo to us during the Friday call
