### ISSUE TITLE
Updates LinkedClaims app to match wireframes

### ISSUE THREAD

**Issue by Gitongamiriam** [Cooperation-org/linked-claims-author#242]
Timeboxed this till Monday 16 and see how much we can get done.

- [x] Landing page (Mobile and PC) -UI
- [x] Sidebar & navbar -UI
- [x] Uploading evidence component (both links and files) -UI
- [ ] Navigation Bugs -Bugs
- [x] Adding "skip button" in the cred form for the non required fields -feat. UI
- [x] Perfecting the evidence preview component (Pics, Videos, PDFs, etc...) -feat. UI
- [x] Adding the featured evidence in the list with it's name -Bugs
- [x] Change the featuring to use up and down buttons to match the wireframes -feat. UI
- [x] Enhancing the (my skills) to [match the wireframes, changing the username and save it in the local db *atleast, adding the ability to continue working on the draft , deleting the vc or draft at well, making sure to add the icons (bluetick for VCs,and logo for the drafts), adding the confirmations for deleting ] -feat UI
- [x] Making the recommender flow in one page form in PC and two steps form in mobile and keeping the uploading component visible as optional in both screens -UI

**Comment by dev-mhany** [comment]
the last point "the recommender deserves to view it's recommendations and edit or delete them the same way as the skills for the issuer in my skills -feat. UI" was a suggestion it wasn't in the wireframe

**Comment by AmrNabel** [comment]
the navigation bugs will leave now because in the skill page there is no navigations, we can discuss on the meet today

**Comment by Gitongamiriam** [comment]
1: Add preview option
2 Fix the dropdown in recommendation  to feature this in the section how do you know this person" Colleague
Friend
Relative
Volunteered together
College
Other
3.

**Comment by Gitongamiriam** [comment]
3. Fix the issue with the profile and support page

**Comment by AmrNabel** [comment]
![Screenshot 2024-12-20 at 5 18 11 PM](https://github.com/user-attachments/assets/ba215989-1909-41fd-87cd-9b4e9bd8103c)
