### ISSUE TITLE
'Sign In'/'Sign Out' button in top right has serif font unlike rest of buttons

### ISSUE THREAD

**Issue by gobengo** [Cooperation-org/linked-claims-author#79]
Expected Behavior:
* all buttons on https://linked-claims-author.vercel.app/ have similar styles i.e. sans-serif font

Actual Behavior:
* button in top right has serif font

Browser:
* Mac OS / Firefox

<img width="823" alt="Screenshot 2024-09-10 at 11 18 04 AM" src="https://github.com/user-attachments/assets/7bbf14e8-84e5-460e-ad59-284759926816">

**Comment by gobengo** [comment]
I still see this on https://opencreds.net/

<img width="1332" alt="Screenshot 2024-12-12 at 11 20 11 AM" src="https://github.com/user-attachments/assets/732dbb48-a12d-4002-9295-37d65bba1623" />

**Comment by gobengo** [comment]
@AmrNabel do you still plan to adjust the Sign In button CSS?

**Comment by AmrNabel** [comment]
![Image](https://github.com/user-attachments/assets/b8c9b3b1-a43a-4492-952e-132ef8cef6ce)
